In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#To laod Dataset 
df=pd.read_csv("iris.csv")

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
#classification algorithm :
#There are 2 types of classification
#1. binary classification : there are 2 classes : yes/no , True/false, 1/0
#2. Multiclass classifier means There are more than 2 classes 

#in the iris dataset , we have 3 classes 
#1. setosa   2. versicolor   3. virginica 

#means there are 3 types of species (setosa, versicolor, virginica).
#here species is a target variable 
#and we have 4 input features : petal length ,petal width and 
#sepal length and sepal width 

In [5]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [6]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [7]:
#To check null values
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [8]:
#To check duplicates rows 
df.duplicated().sum()

3

In [9]:
#To remove duplicates rows
df.drop_duplicates(inplace=True)

In [10]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [11]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [12]:
#Apply LabelEncoder on target variable species 
from sklearn.preprocessing import LabelEncoder
#create object of LabelEncoder class 
le=LabelEncoder()
df['species']=le.fit_transform(df['species'])
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species           int32
dtype: object

In [13]:
#separate input and output 
X=df.drop("species",axis=1) #input variable
Y=df["species"]#output variable

In [14]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [15]:
#split dataset into 70% - 30% 
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,
                                               random_state=1)

In [16]:
X_train.shape,Y_train.shape

((102, 4), (102,))

In [17]:
X_test.shape,Y_test.shape

((45, 4), (45,))

In [18]:
#apply scaling on input X_train and X_test 
from sklearn.preprocessing import StandardScaler
#create object of StandardScaler class
ss=StandardScaler()
X_train=ss.fit_transform(X_train) 
X_test=ss.transform(X_test) 

In [22]:
#We have multiclass classifer dataset (there are 3 classes /categories in 
#this dataset) use classification algorithm 
#1. LogisticRegression 
#call LogisticRegression  class
from sklearn.linear_model import LogisticRegression 

In [23]:
#create object of LogisticRegression  class
lr=LogisticRegression()

In [24]:
#create user defined function 
#create a user defined function 
def create_model(model):
    model.fit(X_train,Y_train) #train the model with 70% data
    #To test the model with 30% data 
    Y_pred=model.predict(X_test)
    #print confusion marix
    print(confusion_matrix(Y_test,Y_pred))
    #generate classification report
    print(classification_report(Y_test,Y_pred))
    return model   

In [25]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [26]:
#call function 
lr=create_model(lr)

[[15  0  0]
 [ 0 15  1]
 [ 0  2 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.94      0.91        16
           2       0.92      0.86      0.89        14

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45



In [ ]:
#DEcisionTreeClassifier 